# Generated by Django 3.0.1 on 2021-01-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_auto_20210103_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='id',
            field=models.AutoField(auto_created=True, default=55, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='electricity',
            field=models.CharField(max_length=20),
        ),
    ]
