# Generated by Django 3.0.1 on 2021-01-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_auto_20210103_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('name', 'electricity', 'age')},
        ),
    ]
