# Generated by Django 3.0.1 on 2021-01-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0005_auto_20210103_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='about',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='name',
        ),
        migrations.AddField(
            model_name='family',
            name='occupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
